### ISSUE TITLE
Plugin can't be load

### ISSUE THREAD

**Issue by alelunardi98** [jefferyto/gedit-control-your-tabs#12]
On Ubuntu 18.04 i followed all steps but when i try to activate the plugin gedit give me an error. It told me that the plugin couldn't be load. I put it in the path specified in the step-by-step installation guide. I tried all 2 the plugin files but i still get the same error.
![Schermata da 2019-05-10 16-48-57](https://user-images.githubusercontent.com/23559086/57536120-d2506d00-7343-11e9-9926-221297d5cf27.png)

**Comment by jefferyto** [comment]
If you start gedit from the command line (in Terminal), then try to enable the plugin, do you see any error messages in Terminal?

**Comment by 1wq2** [comment]
libpeas-WARNING **: 16:46:21.523: The 'python' plugin loader has not been enabled

**Comment by 1wq2** [comment]
yeah, problem with python vs python3. rename file controlyourtabs.plugin.python2 to controlyourtabs.plugin, then open it and change loader to "Loader=python3".

**Comment by jefferyto** [comment]
@1wq2 I think I've described using the correct `.plugin` file in the [installation instructions](https://github.com/jefferyto/gedit-control-your-tabs#installation). Not sure what your issue was?

**Comment by jefferyto** [comment]
@alelunardi98 I can't really help you unless you can provide more information.

**Comment by mirrorsonthewall** [comment]
@alelunardi98 did you copy both the controlyourtabs folder and the .plugin file? I've seen the red cancel sign pic show up when only the .plugin file was copied.

**Comment by jefferyto** [comment]
Since there has been no response for months, I'm closing this. Please reopen if the problem continues.

**Comment by ix4** [comment]
Just FYI I had the same issue until I realized my eyes were playing tricks on me and I had version **3.34** NOT **3.4**
