### ISSUE TITLE
Could we get the tab moving shortcuts as well

### ISSUE THREAD

**Issue by pedrocr** [jefferyto/gedit-control-your-tabs#13]
This issue should have long ago been fixed in Gtk but thanks a lot for this extension. Tabs are finally sane in gedit. Would it be possible to also support Ctrl-Shift-PageUp and Ctrl-Shift-PageDown for tab moving left and right?

**Comment by jefferyto** [comment]
That's not a bad idea :joy: Not sure when I'll have time to implement this but I'll keep it in mind. Thanks for the suggestion!

**Comment by jefferyto** [comment]
It took a while but it's finally done in v0.5.0 - thanks again for the suggestion!
