### ISSUE TITLE
Could We Switch Ctrl+Tab and Ctrl+Page Up (Etc.) In Another Version?

### ISSUE THREAD

**Issue by mirrorsonthewall** [jefferyto/gedit-control-your-tabs#16]
This is how the plugin currently works:
Ctrl+Tab / Ctrl+Shift+Tab - Switch tabs in most recently used order.
Ctrl+Page Up / Ctrl+Page Down - Switch tabs in tab row order.

I would like to switch it to work this way:
Ctrl+Tab / Ctrl+Shift+Tab - Switch tabs in tab row order.
Ctrl+Page Up / Ctrl+Page Down - Switch tabs in most recently used order.

Seems like an easy switch, where in the code could this be flip-flopped?

Use case: Some keyboards don't have a Page Up or Page Down key and can't activate the desired functionality of switching tabs in row order.

**Comment by jefferyto** [comment]
There is a preference you can toggle to use tab row order for Ctrl+Tab. Does it do what you want?

**Comment by mirrorsonthewall** [comment]
Ahh, yes! I missed that!
