### ISSUE TITLE
control your tabs disabled on ubuntu 20.04

### ISSUE THREAD

**Issue by mehdiMj-ir** [jefferyto/gedit-control-your-tabs#18]
Hi. First of all thanks for your amazing plugin. when Ubuntu release a new version I upgrade to 20.04 and  sense then I have problem with control your tabs. 
it's disabled like this:
[image...](https://imgur.com/Dyfa5OR)
I even remove the plugin and replace it again, but didn't work.

**Comment by jefferyto** [comment]
Please see if these instructions will work for you: https://github.com/jefferyto/gedit-control-your-tabs/issues/17#issuecomment-614191017

**Comment by mehdiMj-ir** [comment]
Yes, commenting the line on BOTH tabinfo*.py files fixes the issue :))
