### ISSUE TITLE
Tabbing is currently backwards

### ISSUE THREAD

**Issue by raj45** [jefferyto/gedit-control-your-tabs#5]
It would make sense that Ctrl+tab move to the next tab, and Ctrl+Shift+Tab move to the previous tab, which is the behaviour in all browsers, and opposite to what it is now.

**Comment by jefferyto** [comment]
Ctrl+Tab/Ctrl+Shift+Tab moves between tabs in most recently used order. A future version may allow you to change this to tab row order. If you need to tab row order now, you can use Ctrl+PageUp/Ctrl+PageDown.

**Comment by raj45** [comment]
Thanks for getting back to me, and for the tip. I still think emulating the behavior of browsers would be most user friendly, though.
