### ISSUE TITLE
Wrong plugins path for Gnome 2 in installation instructions.

### ISSUE THREAD

**Issue by Winterwolf** [jefferyto/gedit-control-your-tabs#7]
I copy your plugin to `~/.local/share/gedit/plugins` at linuxmint and not found nothing new in modules list. Right path is `~/.gnome2/gedit/plugins`.

**Comment by jefferyto** [comment]
The current version (v0.2.3) requires gedit 3, and so the installation instructions do not apply for gedit 2 (as you have found). I suggest using v0.1.2 for gedit 2.

**Comment by Winterwolf** [comment]
Yes, I know! I talking about v0.1.2
